# Generated by Django 4.2.9 on 2026-02-28 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_timetable_wizard_overhaul'),
    ]

    operations = [
        migrations.AddField(
            model_name='examschedule',
            name='release_datetime',
            field=models.DateTimeField(blank=True, help_text='Students can view QP and answers after this datetime. Set by HOD, editable anytime before release.', null=True, verbose_name='QP Release Date & Time'),
        ),
        migrations.AddField(
            model_name='qpquestion',
            name='question_image',
            field=models.ImageField(blank=True, help_text='Optional image for this question (diagrams, figures, circuits, etc.)', null=True, upload_to='qp_images/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='revision_number',
            field=models.IntegerField(default=0, help_text='Incremented on each resubmission after rejection'),
        ),
        migrations.AlterField(
            model_name='qpquestion',
            name='question_text',
            field=models.TextField(help_text='Main question text. Use $...$ for inline math, $$...$$ for block math formulas.'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('part', models.CharField(choices=[('A', 'Part A'), ('B', 'Part B'), ('C', 'Part C')], max_length=1)),
                ('marks', models.IntegerField()),
                ('bloom_level', models.CharField(blank=True, max_length=5)),
                ('course_outcome', models.CharField(blank=True, max_length=5)),
                ('exam_session', models.CharField(blank=True, help_text='e.g., NOV/DEC 2024', max_length=50)),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='question_bank_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='main_app.course')),
                ('source_qp', models.ForeignKey(blank=True, help_text='The approved QP this question came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banked_questions', to='main_app.structuredquestionpaper')),
            ],
            options={
                'verbose_name': 'Question Bank Entry',
                'verbose_name_plural': 'Question Bank',
                'db_table': 'main_app_questionbank',
                'ordering': ['-created_at'],
            },
        ),
    ]
