# Generated by Django 4.2.9 on 2026-03-01 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0038_timetable_wizard_overhaul"),
    ]

    operations = [
        migrations.CreateModel(
            name="SameTimeConstraint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="same_time_constraints",
                        to="main_app.timetableconfig",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="same_time_constraints",
                        to="main_app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Same-Time Constraint",
                "verbose_name_plural": "Same-Time Constraints",
                "ordering": ["course__course_code"],
                "unique_together": {("config", "course")},
            },
        ),
    ]
