# Generated by Django 4.2.9 on 2026-03-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_examschedule_release_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='answer_key_comments',
            field=models.TextField(blank=True, help_text='HOD comments on the answer key'),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='answer_key_document',
            field=models.FileField(blank=True, help_text='Answer key document uploaded by faculty after QP approval', null=True, upload_to='answer_keys/structured/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='answer_key_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='answer_key_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='release_datetime',
            field=models.DateTimeField(blank=True, help_text='Date/time after which the QP becomes visible to students. Set by HOD on approval.', null=True),
        ),
    ]
