# Generated by Django 4.2.9 on 2026-03-02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0040_add_faculty_time_block"),
    ]

    operations = [
        migrations.CreateModel(
            name="PECCourseCombinationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_overlap", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pec_combination_rules",
                        to="main_app.timetableconfig",
                    ),
                ),
                (
                    "offering_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pec_rules_as_offering_a",
                        to="main_app.electivecourseoffering",
                    ),
                ),
                (
                    "offering_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pec_rules_as_offering_b",
                        to="main_app.electivecourseoffering",
                    ),
                ),
                (
                    "slot_a_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pec_rules_as_slot_a",
                        to="main_app.course",
                    ),
                ),
                (
                    "slot_b_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pec_rules_as_slot_b",
                        to="main_app.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "PEC Course Combination Rule",
                "verbose_name_plural": "PEC Course Combination Rules",
                "ordering": [
                    "slot_a_course__course_code",
                    "slot_b_course__course_code",
                    "offering_a__actual_course__course_code",
                    "offering_b__actual_course__course_code",
                ],
                "unique_together": {("config", "offering_a", "offering_b")},
            },
        ),
    ]
