# Generated by Django 6.0.1 on 2026-03-14 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0043_account_user_is_staff_alter_academicyear_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetableentry",
            name="lab_assistant",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab assistant for this lab session (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_assistant_entries",
                to="main_app.faculty_profile",
            ),
        ),
    ]
