# Generated by Django 6.0.1 on 2026-03-15 08:51

from django.db import migrations, models


def backfill_program_regulation_mappings(apps, schema_editor):
    Program = apps.get_model("main_app", "Program")
    ProgramRegulation = apps.get_model("main_app", "ProgramRegulation")
    Regulation = apps.get_model("main_app", "Regulation")

    for program in Program.objects.exclude(regulation_id__isnull=True):
        try:
            regulation = Regulation.objects.get(id=program.regulation_id)
        except Regulation.DoesNotExist:
            continue

        ProgramRegulation.objects.get_or_create(
            program_id=program.id,
            regulation_id=regulation.id,
            defaults={
                "effective_from_year": regulation.year,
                "effective_to_year": None,
                "is_active": True,
                "notes": "Backfilled from legacy Program.regulation during migration.",
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0044_add_lab_assistant_to_timetable_entry"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="program",
            name="unique_program_code_per_regulation",
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_program_code"
            ),
        ),
        migrations.RunPython(backfill_program_regulation_mappings, noop_reverse),
    ]
