# Generated by Django 6.0.1 on 2026-03-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0045_program_code_unique_and_backfill_mappings"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramSemesterDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Override start date for this program",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Override end date for this program",
                        null=True,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_dates",
                        to="main_app.program",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_dates",
                        to="main_app.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Semester Date Override",
                "verbose_name_plural": "Program Semester Date Overrides",
                "unique_together": {("semester", "program")},
            },
        ),
    ]
