# Generated by Django 4.2.9 on 2026-03-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0047_course_assignment_unique_by_batch"),
    ]

    operations = []
