# Generated by Django 6.0.1 on 2026-03-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0050_recover_lost_course_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_assignment",
            name="special_note",
            field=models.CharField(
                blank=True,
                help_text="Used to mark quick IOC assignments or other special cases",
                max_length=255,
                null=True,
            ),
        ),
    ]
