# Generated by Django 4.2.9 on 2026-03-21

from django.db import migrations, models


def migrate_hod_designation_to_prof(apps, schema_editor):
    FacultyProfile = apps.get_model('main_app', 'Faculty_Profile')
    FacultyProfile.objects.filter(designation='HOD').update(designation='PROF')


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0052_course_assignment_lit_separate_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty_profile',
            name='designation',
            field=models.CharField(
                choices=[
                    ('AP', 'Assistant Professor'),
                    ('APSR', 'Assistant Professor Sr. Grade (Senior Grade)'),
                    ('APSL', 'Assistant Professor SL Grade (Selection Grade)'),
                    ('ASP', 'Associate Professor'),
                    ('PROF', 'Professor'),
                    ('NTF', 'Non-Teaching Faculty'),
                    ('PA1', 'Professional Assistant - I'),
                    ('PA2', 'Professional Assistant - II'),
                    ('PA3', 'Professional Assistant - III'),
                    ('TECH', 'Technical Assistant'),
                    ('PEON', 'Peon'),
                ],
                default='AP',
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name='faculty_profile',
            name='delete_guest_after_inactive_semesters',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Delete guest when inactive assignment streak is greater than this number of semesters',
            ),
        ),
        migrations.RunPython(migrate_hod_designation_to_prof, migrations.RunPython.noop),
    ]
