# Generated by Django 4.2.9 on 2026-03-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0053_faculty_designation_guest_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="account_user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
    ]
