# Generated by Django 4.2.9 on 2026-03-22 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0054_account_user_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.DecimalField(
                decimal_places=1,
                default=3.0,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
