# Generated by Django 4.2.9 on 2026-03-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0055_alter_course_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_assignment",
            name="practical_in_classroom",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, practical/lab sessions are scheduled in classroom without consuming a physical lab room",
            ),
        ),
    ]
