# Generated by Django 4.2.9 on 2026-04-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0041_structuredqp_submission_checklists"),
        ("main_app", "0056_course_assignment_practical_in_classroom"),
    ]

    operations = []
