# Generated by Django 4.2.9 on 2026-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0057_merge_20260405_1532"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionbank",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
