# Generated by Django 4.2.9 on 2026-04-06 07:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0058_alter_questionbank_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MELabAssistConstraint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester_type",
                    models.CharField(
                        choices=[("ODD", "Odd Semester"), ("EVEN", "Even Semester")],
                        max_length=4,
                    ),
                ),
                (
                    "me_year_of_study",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="me_lab_assist_constraints",
                        to="main_app.academicyear",
                    ),
                ),
                (
                    "be_lab_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="me_lab_assist_constraints",
                        to="main_app.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "me_program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="me_lab_assist_constraints",
                        to="main_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "M.E. Lab Assist Constraint",
                "verbose_name_plural": "M.E. Lab Assist Constraints",
                "ordering": [
                    "me_program__code",
                    "me_year_of_study",
                    "be_lab_course__course_code",
                ],
                "unique_together": {
                    (
                        "academic_year",
                        "semester_type",
                        "me_program",
                        "me_year_of_study",
                        "be_lab_course",
                    )
                },
            },
        ),
    ]
