# Generated by Django 4.2.9 on 2026-03-02 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0040_qp_release_datetime_answer_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleCategoryMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name in Moodle', max_length=200, unique=True)),
                ('moodle_category_id', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lms_integration.moodlecategorymapping')),
            ],
            options={
                'verbose_name': 'Moodle Category Mapping',
                'verbose_name_plural': 'Moodle Category Mappings',
            },
        ),
        migrations.CreateModel(
            name='MoodleCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_course_id', models.PositiveIntegerField(help_text='Moodle internal course id', unique=True)),
                ('moodle_shortname', models.CharField(blank=True, max_length=200)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending Sync'), ('ERROR', 'Sync Error')], default='SYNCED', max_length=10)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms_integration.moodlecategorymapping')),
                ('course_assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_mapping', to='main_app.course_assignment')),
            ],
            options={
                'verbose_name': 'Moodle Course Mapping',
                'verbose_name_plural': 'Moodle Course Mappings',
            },
        ),
        migrations.CreateModel(
            name='MoodleUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_user_id', models.PositiveIntegerField(help_text='Moodle internal user id', unique=True)),
                ('moodle_username', models.CharField(blank=True, max_length=200)),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending Sync'), ('ERROR', 'Sync Error')], default='SYNCED', max_length=10)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moodle User Mapping',
                'verbose_name_plural': 'Moodle User Mappings',
            },
        ),
        migrations.CreateModel(
            name='MoodleSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_USER', 'Created User'), ('UPDATE_USER', 'Updated User'), ('SUSPEND_USER', 'Suspended User'), ('CREATE_COURSE', 'Created Course'), ('ENROL', 'Enrolled User'), ('UNENROL', 'Unenrolled User'), ('PULL_GRADES', 'Pulled Grades'), ('SYNC_ALL', 'Full Sync'), ('TEST_CONNECTION', 'Connection Test')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('detail', models.TextField(blank=True, help_text='Human-readable summary')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moodle Sync Log',
                'verbose_name_plural': 'Moodle Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodleGradeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Grade item label in Moodle', max_length=300)),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('grade_max', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('last_fetched', models.DateTimeField(auto_now=True)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lms_integration.moodlecoursemapping')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Moodle Grade (cached)',
                'verbose_name_plural': 'Moodle Grades (cached)',
            },
        ),
        migrations.CreateModel(
            name='MoodleEnrolmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('editingteacher', 'Teacher (editing)'), ('teacher', 'Teacher (non-editing)')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('unenrolled_at', models.DateTimeField(blank=True, null=True)),
                ('course_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='lms_integration.moodlecoursemapping')),
                ('user_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolments', to='lms_integration.moodleusermapping')),
            ],
            options={
                'verbose_name': 'Moodle Enrolment',
                'verbose_name_plural': 'Moodle Enrolments',
                'unique_together': {('user_mapping', 'course_mapping', 'role')},
            },
        ),
    ]
